# Generated by Django 5.2.16 on 2026-10-05 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Goals',
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='GoalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_auto_complete', models.BooleanField(default=False)),
                ('is_auto_incomplete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_checklists', to='goals.goal')),
            ],
            options={
                'db_table': 'goal_checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_auto_complete', models.BooleanField(default=False)),
                ('is_auto_incomplete', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(blank=True, default=None, null=True)),
                ('is_incomplete', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('goal_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='goals.goalchecklist')),
            ],
            options={
                'db_table': 'checklist_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
